name: Build blackboxExporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'

    - name: Download
      id: download_blackboxExporter
      run: |
        git clone https://github.com/prometheus/blackbox_exporter.git
        cd blackbox_exporter

    - name: Build
      run: |
        cd blackbox_exporter
        go build -ldflags "-s -w"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.latest_tag }}
        release_name: "blackbox_exporter ${{ env.latest_tag }}"
        draft: false
        prerelease: false

    - name: Upload build to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: blackbox_exporter/blackbox_exporter
        asset_name: blackbox_exporter
        asset_content_type: application/octet-stream
