name: Build nodeExporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download
      id: download_nodeExporter
      run: |
        git clone https://github.com/prometheus/node_exporter.git
        cd node_exporter
        git checkout tags/v1.8.2
        echo "latest_tag=v1.8.2" >> $GITHUB_ENV

    - name: Build
      run: |
        cd node_exporter
        go build -ldflags "-s -w"

    - name: Test
      run: |
        cd node_exporter
        go test ./...

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.latest_tag }}
        release_name: "node_exporter ${{ env.latest_tag }}"
        draft: false
        prerelease: false

    - name: Upload build to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: node_exporter/node_exporter
        asset_name: node_exporter
        asset_content_type: application/octet-stream
